### ISSUE TITLE
关于文件被覆盖的问题

### ISSUE THREAD

**Issue by LiaoJingyi** [twoentartian/Matlab_FDD_AnchorLoc#1]
如果因为是word文档的缘故，你的提交直接覆盖了我的文件，那么每次写东西之前先pull一下。
但是我非常怀疑你之前提交的参数有问题，因为hub上的版本比你的版本更高，你的提交应该会被拒绝。

**Comment by twoentartian** [comment]
pull的时候  git无法判断非二进制文件的修改之处 而我的word版本在上一次版本之后 所以gi自动保留了我的本地版本

发自我的小米手机
在 LiaoJingyi notifications@github.com，2016年9月27日 下午7:32写道：

如果因为是word文档的缘故，你的提交直接覆盖了我的文件，那么每次写东西之前先pull一下。
但是我非常怀疑你之前提交的参数有问题，因为hub上的版本比你的版本更高，你的提交应该会被拒绝。

**Comment by LiaoJingyi** [comment]
不，我不是这个意思，我是说你提交的时候可能有些参数缺省。
因为我提交了新的文档之后，hub上的版本比你本地超前。
