### ISSUE TITLE
Remember pull new version!

### ISSUE THREAD

**Issue by LiaoJingyi** [twoentartian/Matlab_FDD_AnchorLoc#2]
Can we have a discussion on Marxism course?
If it is possible, don't forget update new articles!
But I quite doubt that laptop is **banned** in class.  So _back row_ seats are required.
How do you think?

**Comment by twoentartian** [comment]
那个马克思老师太厉害了

发自我的小米手机
在 LiaoJingyi notifications@github.com，2016年10月26日 下午5:49写道：

Can we have a discussion on Marxism course?
If it is possible, don't forget update new articles!
But I quite doubt that laptop is banned in class. So back row seats are required.
How do you think?

**Comment by twoentartian** [comment]
感觉要讨论的话   有点难

发自我的小米手机
在 LiaoJingyi notifications@github.com，2016年10月26日 下午5:49写道：

Can we have a discussion on Marxism course?
If it is possible, don't forget update new articles!
But I quite doubt that laptop is banned in class. So back row seats are required.
How do you think?

**Comment by LiaoJingyi** [comment]
OK.
But, still, you'd better **update**  documents.
- Report
- Papers from IEEE
